### ISSUE TITLE
[Docs] ReadMe 작성

### ISSUE THREAD

**Issue by arinming** [Cherrypickk/ChwitKey-Android#142]
## 설명
프로젝트 설명을 자세히 기재한 ReadMe를 작성합니다.

## To-Do List
- [x] 팀원 소개
- [x] 앱 기능 소개
- [x] 앱 디자인 소개
- [x] 디자인 패턴, 아키텍처 패턴
- [x] 사용한 기술
- [ ] 시연영상
- [x] 컨벤션 링크 변경
- [ ] 개발 기간 기재
